const apiMockSnow = {
  location: {
    name: 'Fairbanks',
    region: 'Alaska',
    country: 'United States of America',
    lat: 64.84,
    lon: -147.72,
    tz_id: 'America/Anchorage',
    localtime_epoch: 1665503285,
    localtime: '2022-10-11 7:48',
  },
  current: {
    last_updated_epoch: 1665503100,
    last_updated: '2022-10-11 07:45',
    temp_c: -2,
    temp_f: 28.4,
    is_day: 0,
    condition: {
      text: 'Light snow',
      icon: '//cdn.weatherapi.com/weather/64x64/night/326.png',
      code: 1213,
    },
    wind_mph: 3.8,
    wind_kph: 6.1,
    wind_degree: 200,
    wind_dir: 'SSW',
    pressure_mb: 1017,
    pressure_in: 30.02,
    precip_mm: 0,
    precip_in: 0,
    humidity: 86,
    cloud: 75,
    feelslike_c: -4.7,
    feelslike_f: 23.6,
    vis_km: 16,
    vis_miles: 9,
    uv: 1,
    gust_mph: 6.7,
    gust_kph: 10.8,
  },
  forecast: {
    forecastday: [
      {
        date: '2022-10-11',
        date_epoch: 1665446400,
        day: {
          maxtemp_c: 0.9,
          maxtemp_f: 33.6,
          mintemp_c: -3.5,
          mintemp_f: 25.7,
          avgtemp_c: -1.8,
          avgtemp_f: 28.7,
          maxwind_mph: 7.2,
          maxwind_kph: 11.5,
          totalprecip_mm: 0.1,
          totalprecip_in: 0,
          avgvis_km: 9.9,
          avgvis_miles: 6,
          avghumidity: 76,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 3,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003,
          },
          uv: 2,
        },
        astro: {
          sunrise: '08:31 AM',
          sunset: '06:42 PM',
          moonrise: '06:43 PM',
          moonset: '11:30 AM',
          moon_phase: 'Full Moon',
          moon_illumination: '100',
        },
        hour: [
          {
            time_epoch: 1665475200,
            time: '2022-10-11 00:00',
            temp_c: -2.2,
            temp_f: 28,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 262,
            wind_dir: 'W',
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 49,
            feelslike_c: -4.3,
            feelslike_f: 24.3,
            windchill_c: -4.3,
            windchill_f: 24.3,
            heatindex_c: -2.2,
            heatindex_f: 28,
            dewpoint_c: -5.1,
            dewpoint_f: 22.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 1,
          },
          {
            time_epoch: 1665478800,
            time: '2022-10-11 01:00',
            temp_c: -2.4,
            temp_f: 27.7,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 251,
            wind_dir: 'WSW',
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 35,
            feelslike_c: -4.8,
            feelslike_f: 23.4,
            windchill_c: -4.8,
            windchill_f: 23.4,
            heatindex_c: -2.4,
            heatindex_f: 27.7,
            dewpoint_c: -5,
            dewpoint_f: 23,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1665482400,
            time: '2022-10-11 02:00',
            temp_c: -2.8,
            temp_f: 27,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 247,
            wind_dir: 'WSW',
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 44,
            feelslike_c: -5.6,
            feelslike_f: 21.9,
            windchill_c: -5.6,
            windchill_f: 21.9,
            heatindex_c: -2.8,
            heatindex_f: 27,
            dewpoint_c: -5,
            dewpoint_f: 23,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1,
          },
          {
            time_epoch: 1665486000,
            time: '2022-10-11 03:00',
            temp_c: -3,
            temp_f: 26.6,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 242,
            wind_dir: 'WSW',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 40,
            feelslike_c: -5.8,
            feelslike_f: 21.6,
            windchill_c: -5.8,
            windchill_f: 21.6,
            heatindex_c: -3,
            heatindex_f: 26.6,
            dewpoint_c: -5.1,
            dewpoint_f: 22.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1,
          },
          {
            time_epoch: 1665489600,
            time: '2022-10-11 04:00',
            temp_c: -3.1,
            temp_f: 26.4,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 237,
            wind_dir: 'WSW',
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 54,
            feelslike_c: -5.9,
            feelslike_f: 21.4,
            windchill_c: -5.9,
            windchill_f: 21.4,
            heatindex_c: -3.1,
            heatindex_f: 26.4,
            dewpoint_c: -5.1,
            dewpoint_f: 22.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1,
          },
          {
            time_epoch: 1665493200,
            time: '2022-10-11 05:00',
            temp_c: -3.2,
            temp_f: 26.2,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 230,
            wind_dir: 'SW',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 67,
            feelslike_c: -6.1,
            feelslike_f: 21,
            windchill_c: -6.1,
            windchill_f: 21,
            heatindex_c: -3.2,
            heatindex_f: 26.2,
            dewpoint_c: -5.1,
            dewpoint_f: 22.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1,
          },
          {
            time_epoch: 1665496800,
            time: '2022-10-11 06:00',
            temp_c: -2.9,
            temp_f: 26.8,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 228,
            wind_dir: 'SW',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 57,
            feelslike_c: -5.7,
            feelslike_f: 21.7,
            windchill_c: -5.7,
            windchill_f: 21.7,
            heatindex_c: -2.9,
            heatindex_f: 26.8,
            dewpoint_c: -4.8,
            dewpoint_f: 23.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1665500400,
            time: '2022-10-11 07:00',
            temp_c: -3.1,
            temp_f: 26.4,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 225,
            wind_dir: 'SW',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 37,
            feelslike_c: -5.9,
            feelslike_f: 21.4,
            windchill_c: -5.9,
            windchill_f: 21.4,
            heatindex_c: -3.1,
            heatindex_f: 26.4,
            dewpoint_c: -4.6,
            dewpoint_f: 23.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
          {
            time_epoch: 1665504000,
            time: '2022-10-11 08:00',
            temp_c: -3.4,
            temp_f: 25.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 232,
            wind_dir: 'SW',
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 20,
            feelslike_c: -6.4,
            feelslike_f: 20.5,
            windchill_c: -6.4,
            windchill_f: 20.5,
            heatindex_c: -3.4,
            heatindex_f: 25.9,
            dewpoint_c: -4.9,
            dewpoint_f: 23.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1,
          },
          {
            time_epoch: 1665507600,
            time: '2022-10-11 09:00',
            temp_c: -3.5,
            temp_f: 25.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 231,
            wind_dir: 'SW',
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 88,
            cloud: 31,
            feelslike_c: -6.5,
            feelslike_f: 20.3,
            windchill_c: -6.5,
            windchill_f: 20.3,
            heatindex_c: -3.5,
            heatindex_f: 25.7,
            dewpoint_c: -5.2,
            dewpoint_f: 22.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 2,
          },
          {
            time_epoch: 1665511200,
            time: '2022-10-11 10:00',
            temp_c: -2.5,
            temp_f: 27.5,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 231,
            wind_dir: 'SW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 37,
            feelslike_c: -5.2,
            feelslike_f: 22.6,
            windchill_c: -5.2,
            windchill_f: 22.6,
            heatindex_c: -2.5,
            heatindex_f: 27.5,
            dewpoint_c: -5.3,
            dewpoint_f: 22.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 2,
          },
          {
            time_epoch: 1665514800,
            time: '2022-10-11 11:00',
            temp_c: -1.3,
            temp_f: 29.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 242,
            wind_dir: 'WSW',
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            humidity: 73,
            cloud: 49,
            feelslike_c: -4,
            feelslike_f: 24.8,
            windchill_c: -4,
            windchill_f: 24.8,
            heatindex_c: -1.3,
            heatindex_f: 29.7,
            dewpoint_c: -5.5,
            dewpoint_f: 22.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 2,
          },
          {
            time_epoch: 1665518400,
            time: '2022-10-11 12:00',
            temp_c: -0.5,
            temp_f: 31.1,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 243,
            wind_dir: 'WSW',
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 83,
            feelslike_c: -3.3,
            feelslike_f: 26.1,
            windchill_c: -3.3,
            windchill_f: 26.1,
            heatindex_c: -0.5,
            heatindex_f: 31.1,
            dewpoint_c: -5.5,
            dewpoint_f: 22.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 1,
          },
          {
            time_epoch: 1665522000,
            time: '2022-10-11 13:00',
            temp_c: 0.2,
            temp_f: 32.4,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 243,
            wind_dir: 'WSW',
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 100,
            feelslike_c: -3,
            feelslike_f: 26.6,
            windchill_c: -3,
            windchill_f: 26.6,
            heatindex_c: 0.2,
            heatindex_f: 32.4,
            dewpoint_c: -5.6,
            dewpoint_f: 21.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
          {
            time_epoch: 1665525600,
            time: '2022-10-11 14:00',
            temp_c: 0.6,
            temp_f: 33.1,
            is_day: 1,
            condition: {
              text: 'Light snow showers',
              icon: '//cdn.weatherapi.com/weather/64x64/day/368.png',
              code: 1255,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 244,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 100,
            feelslike_c: -2.7,
            feelslike_f: 27.1,
            windchill_c: -2.7,
            windchill_f: 27.1,
            heatindex_c: 0.6,
            heatindex_f: 33.1,
            dewpoint_c: -6.4,
            dewpoint_f: 20.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
          {
            time_epoch: 1665529200,
            time: '2022-10-11 15:00',
            temp_c: 0.9,
            temp_f: 33.6,
            is_day: 1,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
              code: 1009,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 249,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 56,
            cloud: 100,
            feelslike_c: -2.6,
            feelslike_f: 27.3,
            windchill_c: -2.6,
            windchill_f: 27.3,
            heatindex_c: 0.9,
            heatindex_f: 33.6,
            dewpoint_c: -6.9,
            dewpoint_f: 19.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1665532800,
            time: '2022-10-11 16:00',
            temp_c: 0.9,
            temp_f: 33.6,
            is_day: 1,
            condition: {
              text: 'Moderate or heavy snow showers',
              icon: '//cdn.weatherapi.com/weather/64x64/day/371.png',
              code: 1258,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 254,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 56,
            cloud: 64,
            feelslike_c: -2.4,
            feelslike_f: 27.7,
            windchill_c: -2.4,
            windchill_f: 27.7,
            heatindex_c: 0.9,
            heatindex_f: 33.6,
            dewpoint_c: -6.8,
            dewpoint_f: 19.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 1,
            chance_of_snow: 79,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 1,
          },
          {
            time_epoch: 1665536400,
            time: '2022-10-11 17:00',
            temp_c: 0.8,
            temp_f: 33.4,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 259,
            wind_dir: 'W',
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 30,
            feelslike_c: -1.9,
            feelslike_f: 28.6,
            windchill_c: -1.9,
            windchill_f: 28.6,
            heatindex_c: 0.8,
            heatindex_f: 33.4,
            dewpoint_c: -6.3,
            dewpoint_f: 20.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 2,
          },
          {
            time_epoch: 1665540000,
            time: '2022-10-11 18:00',
            temp_c: -0.6,
            temp_f: 30.9,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 239,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 34,
            feelslike_c: -2.3,
            feelslike_f: 27.9,
            windchill_c: -2.3,
            windchill_f: 27.9,
            heatindex_c: -0.6,
            heatindex_f: 30.9,
            dewpoint_c: -6.1,
            dewpoint_f: 21,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 2,
          },
          {
            time_epoch: 1665543600,
            time: '2022-10-11 19:00',
            temp_c: -2.1,
            temp_f: 28.2,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 221,
            wind_dir: 'SW',
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            humidity: 73,
            cloud: 59,
            feelslike_c: -3.6,
            feelslike_f: 25.5,
            windchill_c: -3.6,
            windchill_f: 25.5,
            heatindex_c: -2.1,
            heatindex_f: 28.2,
            dewpoint_c: -6.3,
            dewpoint_f: 20.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1665547200,
            time: '2022-10-11 20:00',
            temp_c: -2.6,
            temp_f: 27.3,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 217,
            wind_dir: 'SW',
            pressure_mb: 1022,
            pressure_in: 30.18,
            precip_mm: 0,
            precip_in: 0,
            humidity: 75,
            cloud: 96,
            feelslike_c: -4.6,
            feelslike_f: 23.7,
            windchill_c: -4.6,
            windchill_f: 23.7,
            heatindex_c: -2.6,
            heatindex_f: 27.3,
            dewpoint_c: -6.4,
            dewpoint_f: 20.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 1,
          },
          {
            time_epoch: 1665550800,
            time: '2022-10-11 21:00',
            temp_c: -2.3,
            temp_f: 27.9,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 215,
            wind_dir: 'SW',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 77,
            feelslike_c: -4.2,
            feelslike_f: 24.4,
            windchill_c: -4.2,
            windchill_f: 24.4,
            heatindex_c: -2.3,
            heatindex_f: 27.9,
            dewpoint_c: -5.8,
            dewpoint_f: 21.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 1,
          },
          {
            time_epoch: 1665554400,
            time: '2022-10-11 22:00',
            temp_c: -2.7,
            temp_f: 27.1,
            is_day: 0,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
              code: 1006,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 217,
            wind_dir: 'SW',
            pressure_mb: 1023,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 66,
            feelslike_c: -4.8,
            feelslike_f: 23.4,
            windchill_c: -4.8,
            windchill_f: 23.4,
            heatindex_c: -2.7,
            heatindex_f: 27.1,
            dewpoint_c: -5.3,
            dewpoint_f: 22.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 1,
          },
          {
            time_epoch: 1665558000,
            time: '2022-10-11 23:00',
            temp_c: -3.1,
            temp_f: 26.4,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 210,
            wind_dir: 'SSW',
            pressure_mb: 1023,
            pressure_in: 30.21,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 97,
            feelslike_c: -5.6,
            feelslike_f: 21.9,
            windchill_c: -5.6,
            windchill_f: 21.9,
            heatindex_c: -3.1,
            heatindex_f: 26.4,
            dewpoint_c: -5,
            dewpoint_f: 23,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
        ],
      },
    ],
  },
};

export default apiMockSnow;
