const apiMockWhiteVersion = {
  location: {
    name: 'London',
    region: 'City of London, Greater London',
    country: 'United Kingdom',
    lat: 51.52,
    lon: -0.11,
    tz_id: 'Europe/London',
    localtime_epoch: 1665420327,
    localtime: '2022-10-10 17:45',
  },
  current: {
    last_updated_epoch: 1665419400,
    last_updated: '2022-10-10 17:30',
    temp_c: 15,
    temp_f: 59,
    is_day: 1,
    condition: {
      text: 'Sunny',
      icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
      code: 1000,
    },
    wind_mph: 5.6,
    wind_kph: 9,
    wind_degree: 350,
    wind_dir: 'N',
    pressure_mb: 1022,
    pressure_in: 30.18,
    precip_mm: 0,
    precip_in: 0,
    humidity: 51,
    cloud: 0,
    feelslike_c: 14.1,
    feelslike_f: 57.4,
    vis_km: 10,
    vis_miles: 6,
    uv: 5,
    gust_mph: 10.3,
    gust_kph: 16.6,
  },
  forecast: {
    forecastday: [
      {
        date: '2022-10-10',
        date_epoch: 1665360000,
        day: {
          maxtemp_c: 17.4,
          maxtemp_f: 63.3,
          mintemp_c: 10.9,
          mintemp_f: 51.6,
          avgtemp_c: 13.9,
          avgtemp_f: 57,
          maxwind_mph: 11,
          maxwind_kph: 17.6,
          totalprecip_mm: 2.6,
          totalprecip_in: 0.1,
          avgvis_km: 9.3,
          avgvis_miles: 5,
          avghumidity: 60,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 98,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Patchy rain possible',
            icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
            code: 1063,
          },
          uv: 3,
        },
        astro: {
          sunrise: '07:16 AM',
          sunset: '06:18 PM',
          moonrise: '06:42 PM',
          moonset: '07:43 AM',
          moon_phase: 'Full Moon',
          moon_illumination: '100',
        },
        hour: [
          {
            time_epoch: 1665356400,
            time: '2022-10-10 00:00',
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 189,
            wind_dir: 'S',
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 6,
            feelslike_c: 12.2,
            feelslike_f: 54,
            windchill_c: 12.2,
            windchill_f: 54,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            dewpoint_c: 6.9,
            dewpoint_f: 44.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1665360000,
            time: '2022-10-10 01:00',
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 211,
            wind_dir: 'SSW',
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 13,
            feelslike_c: 12.3,
            feelslike_f: 54.1,
            windchill_c: 12.3,
            windchill_f: 54.1,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            dewpoint_c: 7.6,
            dewpoint_f: 45.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1,
          },
          {
            time_epoch: 1665363600,
            time: '2022-10-10 02:00',
            temp_c: 12.6,
            temp_f: 54.7,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 212,
            wind_dir: 'SSW',
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 50,
            feelslike_c: 12.5,
            feelslike_f: 54.5,
            windchill_c: 12.5,
            windchill_f: 54.5,
            heatindex_c: 12.6,
            heatindex_f: 54.7,
            dewpoint_c: 7.8,
            dewpoint_f: 46,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1,
          },
          {
            time_epoch: 1665367200,
            time: '2022-10-10 03:00',
            temp_c: 12.8,
            temp_f: 55,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 223,
            wind_dir: 'SW',
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 70,
            cloud: 100,
            feelslike_c: 12.9,
            feelslike_f: 55.2,
            windchill_c: 12.9,
            windchill_f: 55.2,
            heatindex_c: 12.8,
            heatindex_f: 55,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
          {
            time_epoch: 1665370800,
            time: '2022-10-10 04:00',
            temp_c: 13.1,
            temp_f: 55.6,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 214,
            wind_dir: 'SW',
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 58,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            windchill_c: 13.3,
            windchill_f: 55.9,
            heatindex_c: 13.1,
            heatindex_f: 55.6,
            dewpoint_c: 7.6,
            dewpoint_f: 45.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
          {
            time_epoch: 1665374400,
            time: '2022-10-10 05:00',
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 269,
            wind_dir: 'W',
            pressure_mb: 1011,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 100,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            windchill_c: 13.3,
            windchill_f: 55.9,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            dewpoint_c: 8.1,
            dewpoint_f: 46.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 1,
          },
          {
            time_epoch: 1665378000,
            time: '2022-10-10 06:00',
            temp_c: 12.7,
            temp_f: 54.9,
            is_day: 0,
            condition: {
              text: 'Overcast',
              icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
              code: 1009,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 308,
            wind_dir: 'NW',
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0,
            precip_in: 0,
            humidity: 78,
            cloud: 100,
            feelslike_c: 11.8,
            feelslike_f: 53.2,
            windchill_c: 11.8,
            windchill_f: 53.2,
            heatindex_c: 12.7,
            heatindex_f: 54.9,
            dewpoint_c: 8.9,
            dewpoint_f: 48,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1665381600,
            time: '2022-10-10 07:00',
            temp_c: 12,
            temp_f: 53.6,
            is_day: 0,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/night/266.png',
              code: 1153,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 334,
            wind_dir: 'NNW',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 83,
            cloud: 100,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            windchill_c: 10.3,
            windchill_f: 50.5,
            heatindex_c: 12,
            heatindex_f: 53.6,
            dewpoint_c: 9.2,
            dewpoint_f: 48.6,
            will_it_rain: 1,
            chance_of_rain: 98,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 13,
            gust_kph: 20.9,
            uv: 1,
          },
          {
            time_epoch: 1665385200,
            time: '2022-10-10 08:00',
            temp_c: 11.1,
            temp_f: 52,
            is_day: 1,
            condition: {
              text: 'Light drizzle',
              icon: '//cdn.weatherapi.com/weather/64x64/day/266.png',
              code: 1153,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 352,
            wind_dir: 'N',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 85,
            cloud: 100,
            feelslike_c: 9.3,
            feelslike_f: 48.7,
            windchill_c: 9.3,
            windchill_f: 48.7,
            heatindex_c: 11.1,
            heatindex_f: 52,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 67,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 3,
          },
          {
            time_epoch: 1665388800,
            time: '2022-10-10 09:00',
            temp_c: 12.2,
            temp_f: 54,
            is_day: 1,
            condition: {
              text: 'Patchy light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/293.png',
              code: 1180,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 350,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 1.1,
            precip_in: 0.04,
            humidity: 69,
            cloud: 54,
            feelslike_c: 10.6,
            feelslike_f: 51.1,
            windchill_c: 10.6,
            windchill_f: 51.1,
            heatindex_c: 12.2,
            heatindex_f: 54,
            dewpoint_c: 6.8,
            dewpoint_f: 44.2,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 3,
          },
          {
            time_epoch: 1665392400,
            time: '2022-10-10 10:00',
            temp_c: 13.4,
            temp_f: 56.1,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 345,
            wind_dir: 'NNW',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 60,
            cloud: 75,
            feelslike_c: 12,
            feelslike_f: 53.6,
            windchill_c: 12,
            windchill_f: 53.6,
            heatindex_c: 13.4,
            heatindex_f: 56.1,
            dewpoint_c: 5.9,
            dewpoint_f: 42.6,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 3,
          },
          {
            time_epoch: 1665396000,
            time: '2022-10-10 11:00',
            temp_c: 15,
            temp_f: 59,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 342,
            wind_dir: 'NNW',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 49,
            cloud: 84,
            feelslike_c: 13.9,
            feelslike_f: 57,
            windchill_c: 13.9,
            windchill_f: 57,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.3,
            gust_kph: 19.8,
            uv: 4,
          },
          {
            time_epoch: 1665399600,
            time: '2022-10-10 12:00',
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 1,
            condition: {
              text: 'Patchy rain possible',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 340,
            wind_dir: 'NNW',
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 44,
            cloud: 85,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 3.6,
            dewpoint_f: 38.5,
            will_it_rain: 1,
            chance_of_rain: 81,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 4,
          },
          {
            time_epoch: 1665403200,
            time: '2022-10-10 13:00',
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 11,
            wind_kph: 17.6,
            wind_degree: 340,
            wind_dir: 'NNW',
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 43,
            cloud: 0,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.5,
            gust_kph: 20.2,
            uv: 5,
          },
          {
            time_epoch: 1665406800,
            time: '2022-10-10 14:00',
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 338,
            wind_dir: 'NNW',
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            humidity: 43,
            cloud: 0,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 4.3,
            dewpoint_f: 39.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 5,
          },
          {
            time_epoch: 1665410400,
            time: '2022-10-10 15:00',
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 338,
            wind_dir: 'NNW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 42,
            cloud: 0,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 5,
          },
          {
            time_epoch: 1665414000,
            time: '2022-10-10 16:00',
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 344,
            wind_dir: 'NNW',
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 43,
            cloud: 0,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 4.7,
            dewpoint_f: 40.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.3,
            gust_kph: 16.6,
            uv: 5,
          },
          {
            time_epoch: 1665417600,
            time: '2022-10-10 17:00',
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 344,
            wind_dir: 'NNW',
            pressure_mb: 1022,
            pressure_in: 30.19,
            precip_mm: 0,
            precip_in: 0,
            humidity: 48,
            cloud: 0,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 6.2,
            dewpoint_f: 43.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 5,
          },
          {
            time_epoch: 1665421200,
            time: '2022-10-10 18:00',
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 347,
            wind_dir: 'NNW',
            pressure_mb: 1024,
            pressure_in: 30.23,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 0,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 6.8,
            dewpoint_f: 44.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 5,
          },
          {
            time_epoch: 1665424800,
            time: '2022-10-10 19:00',
            temp_c: 16.1,
            temp_f: 61,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 354,
            wind_dir: 'N',
            pressure_mb: 1024,
            pressure_in: 30.25,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 0,
            feelslike_c: 16.1,
            feelslike_f: 61,
            windchill_c: 16.1,
            windchill_f: 61,
            heatindex_c: 16.1,
            heatindex_f: 61,
            dewpoint_c: 6.7,
            dewpoint_f: 44.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 1,
          },
          {
            time_epoch: 1665428400,
            time: '2022-10-10 20:00',
            temp_c: 12.4,
            temp_f: 54.3,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 350,
            wind_dir: 'N',
            pressure_mb: 1025,
            pressure_in: 30.27,
            precip_mm: 0,
            precip_in: 0,
            humidity: 56,
            cloud: 0,
            feelslike_c: 11.4,
            feelslike_f: 52.5,
            windchill_c: 11.4,
            windchill_f: 52.5,
            heatindex_c: 12.4,
            heatindex_f: 54.3,
            dewpoint_c: 3.8,
            dewpoint_f: 38.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1,
          },
          {
            time_epoch: 1665432000,
            time: '2022-10-10 21:00',
            temp_c: 11.9,
            temp_f: 53.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 349,
            wind_dir: 'N',
            pressure_mb: 1026,
            pressure_in: 30.29,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 6,
            feelslike_c: 10.9,
            feelslike_f: 51.6,
            windchill_c: 10.9,
            windchill_f: 51.6,
            heatindex_c: 11.9,
            heatindex_f: 53.4,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1665435600,
            time: '2022-10-10 22:00',
            temp_c: 11.4,
            temp_f: 52.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 348,
            wind_dir: 'NNW',
            pressure_mb: 1026,
            pressure_in: 30.31,
            precip_mm: 0,
            precip_in: 0,
            humidity: 58,
            cloud: 11,
            feelslike_c: 10.6,
            feelslike_f: 51.1,
            windchill_c: 10.6,
            windchill_f: 51.1,
            heatindex_c: 11.4,
            heatindex_f: 52.5,
            dewpoint_c: 3.5,
            dewpoint_f: 38.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 1,
          },
          {
            time_epoch: 1665439200,
            time: '2022-10-10 23:00',
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 344,
            wind_dir: 'NNW',
            pressure_mb: 1027,
            pressure_in: 30.32,
            precip_mm: 0,
            precip_in: 0,
            humidity: 61,
            cloud: 6,
            feelslike_c: 10.1,
            feelslike_f: 50.2,
            windchill_c: 10.1,
            windchill_f: 50.2,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            dewpoint_c: 3.7,
            dewpoint_f: 38.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
        ],
      },
    ],
  },
};

export default apiMockWhiteVersion;
